### ISSUE TITLE
[Zadanie] Napisać nową klasę która obsłuży inne API - dowolne

### ISSUE THREAD

**Issue by mmswiderski** [mmswiderski/psat-php#11]

**Comment by mmswiderski** [comment]
strona nbp.pl ma jakieś api ale xml...
Dla przykładu notowania z dzisiaj pobieramy tak: http://www.nbp.pl/kursy/xml/a051z160315.xml
Pod tym linkiem więcej info: http://www.nbp.pl/home.aspx?f=/kursy/instrukcja_pobierania_kursow_walut.html

**Comment by cprezes** [comment]
ściemniłem API NBP Tak jak umiałem, czekam na video o Odwróceniu sterowania :+1: :)

**Comment by mmswiderski** [comment]
Wideo konwertuje się do jakiegoś rozsądnego rozmiaru, na szczęście tym razem złapało cały ekran.

**Comment by mmswiderski** [comment]
Będzie powtórka bo się nie nagrało - właśnie kończę konfigurację nowego systemu na lapku :)
