### ISSUE TITLE
zadanie domowe

### ISSUE THREAD

**Issue by borowskiw** [mmswiderski/psat-php#4]
nie działa dalej,

 ale walczę..ten github też nowy twór dla mnie..

**Comment by mmswiderski** [comment]
Wszystko na początku nowe. Możemy jutro się na jakąś kawę zmowic wezmę lapka.

**Comment by mmswiderski** [comment]
Zmieniłem opis w README także powinno się trochę rozjaśnić. 
Dodatkowo dodałem commit, z poprawkami.
