### ISSUE TITLE
[Zadanie] Formatowanie danych zwracanych z API i ich cacheowanie

### ISSUE THREAD

**Issue by mmswiderski** [mmswiderski/psat-php#7]
https://laravel.com/docs/5.2/cache#obtaining-a-cache-instance

**Comment by bwojtyla** [comment]
strona nbp.pl ma jakieś api ale xml... 
Dla przykładu notowania z dzisiaj pobieramy tak: http://www.nbp.pl/kursy/xml/a051z160315.xml 
Pod tym linkiem więcej info: http://www.nbp.pl/home.aspx?f=/kursy/instrukcja_pobierania_kursow_walut.html

**Comment by mmswiderski** [comment]
Zajmiemy się tematem innych API, na razie skupiamy się na zadaniu :)
